#!/bin/sh
#######################
#|VIRTEXT VERSION 1.0|#
#|CREATE BY TAMPANSKY|#
#|PLease Support ME_-|#
#######################
#colors
blue='\e[1;34m'
cyan='\e[0;36m'
green='\e[0;34m'
okegreen='\033[92m'
lightgreen='\e[1;32m'
grey="\033[0;37m"
purple="\033[0;35m"
yellow="\033[1;33m"
Purple="\033[0;35m"
Cafe="\033[0;33m"
Fiuscha="\033[0;35m"
mon="mon"
lightcyan='\e[96m'
white='\e[1;37m'
nc="\e[0m"
red='\e[1;31m'
yellow='\e[1;33m'
clear
#######################
#|VIRTEXT VERSION 1.0|#
#|CREATE BY TAMPANSKY|#
#|PLease Support ME_-|#
#######################
damnika(){
    echo -e $blue "Menunggu Ea Boedjank"
    sleep 1.25
    echo -e $blue "Membuat Folder..."
    wget https://github.com/tampansky/kumpulan-jomblo/blob/master/virtex01.txt
}
PSCT(){
    echo -e $blue "Menunggu Ea Boedjank"
    sleep 1.25
    echo -e $blue "Membuat Folder..."
    wget https://github.com/tampansky/kumpulan-jomblo/blob/master/virtext02.txt
}
RED(){
    echo -e $blue "Menunggu Ea Boedjank"
    sleep 1.25
    echo -e $blue "Membuat Folder..."
    wget https://github.com/tampansky/kumpulan-jomblo/blob/master/virtext03.txt
}
Net(){
    echo -e $blue "Menunggu Ea Boedjank"
    sleep 1.25
    echo -e $blue "Membuat Folder..."
    wget https://github.com/tampansky/kumpulan-jomblo/blob/master/virtext04.txt
}
Not(){
    echo -e $blue "Menunggu Ea Boedjank"
    sleep 1.25
    echo -e $blue "Membuat Folder..."
    wget https://github.com/tampansky/fileku/blob/master/virtext05.txt
}
virtext(){
    echo -e $blue "Menunggu Ea Boedjank"
    sleep 1.25
    echo -e $blue "Membuat Folder..."
    wget https://github.com/tampansky/kumpulan-jomblo/blob/master/virtext06.txt
}
di(){
    echo -e $blue "Menunggu Ea Boedjank"
    sleep 1.25
    echo -e $blue "Membuat Folder..."
    wget https://github.com/tampansky/kumpulan-jomblo/blob/master/virtext07.txt
}
a(){
    echo -e $blue "Menunggu Ea Boedjank"
    sleep 1.25
    echo -e $blue "Membuat Folder..."
    wget https://github.com/tampansky/kumpulan-jomblo/blob/master/virtext08.txt
}
b(){
    echo -e $blue "Menunggu Ea Boedjank"
    sleep 1.25
    echo -e $blue "Membuat Folder..."
    wget https://github.com/tampansky/kumpulan-jomblo/blob/master/virtext09.txt
}
c(){
    echo -e $blue "Menunggu Ea Boedjank"
    sleep 1.25
    echo -e $blue "Membuat Folder..."
    wget https://github.com/tampansky/kumpulan-jomblo/blob/master/virtext10.txt
}
d(){
    echo -e $blue "Menunggu Ea Boedjank"
    sleep 1.25
    echo -e $blue "Membuat Folder..."
    wget https://github.com/tampansky/kumpulan-jomblo/blob/master/virtext11.txt
}
e(){
    echo -e $blue "Menunggu Ea Boedjank"
    sleep 1.25
    echo -e $blue "Membuat Folder..."
    wget https://github.com/tampansky/kumpulan-jomblo/blob/master/virtext12.txt
}
f(){
    echo -e $blue "Menunggu Ea Boedjank"
    sleep 1.25
    echo -e $blue "Membuat Folder..."
    wget https://github.com/tampansky/kumpulan-jomblo/blob/master/virtext13.txt
}
g(){
    echo -e $blue "Menunggu Ea Boedjank"
    sleep 1.25
    echo -e $blue "Membuat Folder..."
    wget https://github.com/tampansky/kumpulan-jomblo/blob/master/virtext14.txt
}
h(){
    echo -e $blue "Menunggu Ea Boedjank"
    sleep 1.25
    echo -e $blue "Membuat Folder..."
    wget https://github.com/tampansky/kumpulan-jomblo/blob/master/virtext15.txt
}
i(){
    echo -e $blue "Menunggu Ea Boedjank"
    sleep 1.25
    echo -e $blue "Membuat Folder..."
    wget https://github.com/tampansky/kumpulan-jomblo/blob/master/virtext16.txt
}
j(){
    echo -e $blue "Menunggu Ea Boedjank"
    sleep 1.25
    echo -e $blue "Membuat Folder..."
    wget https://github.com/tampansky/kumpulan-jomblo/blob/master/virtext17.txt

}
k(){
    echo -e $blue "Menunggu Ea Boedjank"
    sleep 1.25
    echo -e $blue "Membuat Folder..."
    wget https://github.com/tampansky/kumpulan-jomblo/blob/master/virtext18.txt
}
l(){
    echo -e $blue "Menunggu Ea Boedjank"
    sleep 1.25
    echo -e $blue "Membuat Folder..."
    wget https://github.com/tampansky/kumpulan-jomblo/blob/master/virtext19.txt
}
m(){
    echo -e $blue "Menunggu Ea Boedjank"
    sleep 1.25
    echo -e $blue "Membuat Folder..."
    wget https://github.com/tampansky/kumpulan-jomblo/blob/master/virtext20.txt
}
n(){
    echo -e $blue "Menunggu Ea Boedjank"
    sleep 1.25
    echo -e $blue "Membuat Folder..."
    wget https://github.com/tampansky/kumpulan-jomblo/blob/master/virtext21.txt
}
o(){
    echo -e $blue "Menunggu Ea Boedjank"
    sleep 1.25
    echo -e $blue "Membuat Folder..."
    wget https://github.com/tampansky/kumpulan-jomblo/blob/master/virtext22.txt
}
p(){
    echo -e $blue "Menunggu Ea Boedjank"
    sleep 1.25
    echo -e $blue "Membuat Folder..."
    wget https://github.com/tampansky/kumpulan-jomblo/blob/master/virtext23.txt
}
q(){
    echo -e $blue "Menunggu Ea Boedjank"
    sleep 1.25
    echo -e $blue "Membuat Folder..."
    wget https://github.com/tampansky/kumpulan-jomblo/blob/master/virtext24.txt
}
r(){
    echo -e $blue "Menunggu Ea Boedjank"
    sleep 1.25
    echo -e $blue "Membuat Folder..."
    wget https://github.com/tampansky/kumpulan-jomblo/blob/master/virtext25.txt
}
load(){
clear
echo -e $red "MENGHUBUNGKAN..."
sleep 0.25
clear
echo -e $blue "MENGHUBUNGKAN..."
sleep 0.25
clear
echo -e $red "MENGHUBUNGKAN..."
sleep 0.25
clear
echo -e $blue "MENGHUBUNGKAN..."
sleep 0.25
clear
echo -e $red "MENGHUBUNGKAN..."
sleep 0.25        
}
banner(){
    echo -e " ___ ___ __        __                __ "  | lolcat
    sleep 0.25
    echo -e "|   |   |__|.----.|  |_.-----.--.--.|  |_ " | lolcat
    sleep 0.30
    echo -e "|   |   |  ||   _||   _|  -__|_   _||   _|" | lolcat
    sleep 0.25
    echo -e " \_____/|__||__|  |____|_____|__.__||____|" |lolcat 
    sleep 1                                     
}
install(){
    sleep 0.25
    clear
    pkg install ruby -y
    sleep 0.25
    clear 
    gem install lolcat 
    clear
    pkg install wget
}
load
install
    load
sleep 0.25
echo ""
echo -e $red "_____ $blue _____ $red _____ $blue _____"
sleep 0.25
echo -e $lightgreen "Author : $lightcyan HadiPrasetia"
sleep 0.25
echo -e $red "Email : $blue Tampanskyyt@gmail.com"
sleep 0.25
echo -e $lightgreen "Nomor Whatsapp : $lightcyan 087887986528"
sleep 0.25
echo -e $red "Thanks To $blue Suport Me "
sleep 0.25
echo -e $lightgreen "Thanks Assyfa Mawarni And My Mother"
sleep 0.25
echo -e $red "_____ $blue _____ $red _____ $blue _____"
sleep 0.25
echo ""
sleep 5
clear
    banner
    echo -e $blue "SELAMAT MENGGUNAKAN VIRTEXT:v"
    echo -e $cyan "===============$blue==============="
    echo -e $blue "[1] VIRTEXT 01 $cyan [2] VIRTEXT 02"
    echo -e $cyan "[3] VIRTEXT 03 $blue [4] VIRTEXT 04"
    echo -e $blue "[5] VIRTEXT 05 $cyan [6] VIRTEXT 06"
    echo -e $cyan "[7] VIRTEXT 07 $blue [8] VIRTEXT 08"
    echo -e $blue "[9] VIRTEXT 09 $cyan [10] VIRTEXT 10"
    echo -e $cyan "[11] VIRTEXT 11 $blue [12] VIRTEXT 12"
    echo -e $blue "[13] VIRTEXT 13 $cyan [14] VIRTEXT 14"
    echo -e $cyan "[15] VIRTEXT 15 $blue [16] VIRTEXT 16"
    echo -e $blue "[17] VIRTEXT 17 $cyan [18] VIRTEXT 18"
    echo -e $cyan "[19] VIRTEXT 19 $blue [20] VIRTEXT 20"
    echo -e $blue "[21] VIRTEXT 21 $cyan [22] VIRTEXT 22"
    echo -e $cyan "[23] VIRTEXT 23 $blue [24] VIRTEXT 25"
    echo -e $blue "[25] VIRTEXT 25 $cyan [26] KELUAR/Exit."
    echo -e $cyan "===============$blue==============="
    echo -n -e "$blue root$white@$lightgreen./virtext$white:$red~$cyan # $nc"
    read -e lol
    case $lol in
("1")
damnika
clear
    load
       echo -e $green "selesai"
;;
("2")
PSCT
clear
    load
       echo -e $green "selesai"
;;
("3")
RED
clear
    load
       echo -e $green "selesai"
;;
("4")
Not
clear
    load
       echo -e $green "selesai"
;;
("5")
Net
clear
    load
       echo -e $green "selesai"
;;
("6")
virtext
clear
    load
       echo -e $green "selesai"
;;
("7")
di
clear
    load
       echo -e $green "selesai"
;;
("8")
a
clear
    load
       echo -e $green "selesai"
;;
("9")
b
clear
    load
       echo -e $green "selesai"
;;
("10")
c 
clear
    load
       echo -e $green "selesai"
;;
("11")
d 
clear
    load
       echo -e $green "selesai"
;;
("12")
 e
  clear
    load
       echo -e $green "selesai"
;;
("13")
f 
clear
    load
       echo -e $green "selesai"
;;
("14")
g 
clear
    load
       echo -e $green "selesai"
;;
("15")
h 
clear
    load
       echo -e $green "selesai"
;;
("16")
i 
clear
    load
       echo -e $green "selesai"
;;
("17")
j 
clear
    load
       echo -e $green "selesai"
;;
("18")
k 
clear
    load
       echo -e $green "selesai"
;;
("19")
l 
clear
    load
       echo -e $green "selesai"
;;
("20")
m 
clear
    load
       echo -e $green "selesai"
;;
("21")
n 
clear
    load
       echo -e $green "selesai"
;;
("22")
o 
clear
    load
       echo -e $green "selesai"
;;
("23")
p 
clear
    load
       echo -e $green "selesai"
;;
("24")
q 
clear
    load
       echo -e $green "selesai"
;;
("25")
r 
clear
    load
       echo -e $green "selesai"
;;
esac 
