#!/bin/sh
#######################
#|VIRTEXT VERSION 1.0|#
#|CREATE BY TAMPANSKY|#
#|PLease Support ME_-|#
#######################
#colors
blue='\e[1;34m'
cyan='\e[0;36m'
green='\e[0;34m'
okegreen='\033[92m'
lightgreen='\e[1;32m'
grey="\033[0;37m"
purple="\033[0;35m"
yellow="\033[1;33m"
Purple="\033[0;35m"
Cafe="\033[0;33m"
Fiuscha="\033[0;35m"
mon="mon"
lightcyan='\e[96m'
white='\e[1;37m'
nc="\e[0m"
red='\e[1;31m'
yellow='\e[1;33m'
clear
#######################
#|VIRTEXT VERSION 1.0|#
#|CREATE BY TAMPANSKY|#
#|PLease Support ME_-|#
#######################
damnika(){
    echo -e $blue "Menunggu Ea Boedjank"
    sleep 1.25
    echo -e $blue "Membuat Folder..."
    wget https://github.com/tampansky/fileku/blob/master/Virtex01.txt
}
PSCT(){
    echo -e $blue "Menunggu Ea Boedjank"
    sleep 1.25
    echo -e $blue "Membuat Folder..."
    wget https://github.com/tampansky/fileku/blob/master/Virtext02.txt
}
RED(){
    echo -e $blue "Menunggu Ea Boedjank"
    sleep 1.25
    echo -e $blue "Membuat Folder..."
    wget https://github.com/tampansky/fileku/blob/master/Virtext03.txt
}
Net(){
    echo -e $blue "Menunggu Ea Boedjank"
    sleep 1.25
    echo -e $blue "Membuat Folder..."
 wget https://github.com/tampansky/fileku/blob/master/virtext04.txt
}
Not(){
    echo -e $blue "Menunggu Ea Boedjank"
    sleep 1.25
    echo -e $blue "Membuat Folder..."
   wget https://github.com/tampansky/fileku/blob/master/virtext05.txt
}
load(){
clear
echo -e $red "MENGHUBUNGKAN..."
sleep 0.25
clear
echo -e $blue "MENGHUBUNGKAN..."
sleep 0.25
clear
echo -e $red "MENGHUBUNGKAN..."
sleep 0.25
clear
echo -e $blue "MENGHUBUNGKAN..."
sleep 0.25
clear
echo -e $red "MENGHUBUNGKAN..."
sleep 0.25        
}
install(){
    sleep 0.25
    clear
    pkg install ruby -y
    sleep 0.25
    clear 
    gem install lolcat 
    clear
    pkg install wget
}
load
install
    load
    clear
    echo -e $blue "SELAMAT MENGGUNAKAN VIRTEXT:v"
    echo -e $cyan "_-_-_-_-_-_-_-_-_-_-_ $blue -_-_-_-_-_-_-_-_-_-_-_"
    echo -e $blue "[1] VIRTEXT 01 $cyan [2] VIRTEXT 02"
    echo -e $cyan "[3] VIRTEXT 03 $blue [4] VIRTEXT 04"
    echo -e $blue "[5] VIRTEXT 05 $cyan [6] EXIT.     "
    echo -e $cyan "_-_-_-_-_-_-_-_-_-_-_ $blue -_-_-_-_-_-_-_-_-_-_-_"
    echo -n -e "$yellow root$white@$lightgreen/webdav$white:$red~$cyan # $nc"
    read -e lol
    case $lol in
    ("1")
    damnika
    ;;
    ("2")
    PSCT
    ;;
    ("3")
    RED
    ;;
    ("4")
    Net
    ;;
    ("5")
    Not
    ;;
    ("6")
    load
    clear
    ;;
    esac
